version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: meli_postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  db_init:
    build:
      context: ./services/db
    container_name: meli_db_init
    restart: on-failure
    depends_on:
      - postgres_db
    environment:
      DATABASE_URL: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}"

volumes:
  postgres_data:
